// AUTO-GENERATED by tools/png_to_lvgl.py - do not edit.
#pragma once
#include <lvgl.h>

extern const lv_img_dsc_t avatar_placeholder;
extern const lv_img_dsc_t hero_token;
extern const lv_img_dsc_t hero_wifi;
extern const lv_img_dsc_t logo_pd;
extern const lv_img_dsc_t sev_p1;
extern const lv_img_dsc_t sev_p2;
extern const lv_img_dsc_t sev_p3;
extern const lv_img_dsc_t sev_p4;
extern const lv_img_dsc_t sev_p5;
